// <auto-generated />
using BackendProje.Data.Concrete.EFCore.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendProje.Data.Migrations
{
    [DbContext(typeof(BackEndContext))]
    [Migration("20230717223255_InitialDb")]
    partial class InitialDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("BackendProje.Entity.Concrete.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "İstanbul",
                            Count = 25,
                            Status = true
                        },
                        new
                        {
                            Id = 2,
                            Address = "Ankara",
                            Count = 50,
                            Status = true
                        },
                        new
                        {
                            Id = 3,
                            Address = "İzmir",
                            Count = 0,
                            Status = false
                        });
                });

            modelBuilder.Entity("BackendProje.Entity.Concrete.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Telefon",
                            Price = 17000m,
                            Status = true
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bilgisayar",
                            Price = 17000m,
                            Status = true
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tablet",
                            Price = 17000m,
                            Status = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
